services:
  spring:
    image: ghcr.io/giannicapocci/devops-spring:1.0
    container_name: spring
    build:
      context: .
      dockerfile: nonroot.Dockerfile
    ports:
      - "9090:9090"
    environment:
      SPRING_MAIL_USERNAME: ${EMAIL}
      SPRING_MAIL_PASSWORD: ${EMAIL_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      FILE_UPLOAD_DIR: /app/src/main/resources/static/uploads
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - spring-boot-app
    volumes:
      - uploads-data:/app/src/main/resources/static/uploads

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - spring-boot-app
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p$$MYSQL_ROOT_PASSWORD","--protocol","tcp" ]
      start_period: 180s
      timeout: 240s
      retries: 10

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./assets/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spring
    networks:
      - spring-boot-app

networks:
  spring-boot-app:

volumes:
  mysql-data:
  uploads-data:
